blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogDeleteView, BlogUpdateView, BlogDetailView, BlogListView

app_name = BlogConfig.name
urlpatterns = [
    path("blog/", BlogCreateView.as_view(), name="blog_create"),
    path("blog_list/blog/", BlogListView.as_view(), name="blog_list"),
    path("blog_detail/blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("edit/blog/<int:pk>/", BlogUpdateView.as_view(), name="blog_edit"),
    path("delete/blog/<int:pk>/",BlogDeleteView.as_view(), name="blog_delete"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="заголовок")
    slug = models.CharField(max_length=100, verbose_name="slug")
    content = models.TextField(verbose_name='содержимое')
    image_preview = models.ImageField(
        upload_to="blog/image",
        verbose_name="предварительный просмотр",
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")
    is_published = models.BooleanField(default=False, verbose_name="опубликованные посты")
    views_count = models.PositiveIntegerField(default=0, verbose_name="количество просмотров")

    def __str__(self):
        return f"{self.title}: {self.content}"

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ["title", "slug"]

blog/forms.py
from django import forms
from blog.models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'is_published']

blog/views.py
from django.shortcuts import render
from django.utils.text import slugify

from blog.forms import BlogForm
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, TemplateView, CreateView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm

    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("blog:blog_detail", args=[self.object.pk])


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        return obj


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm
    #fields = ['title', 'content', 'is_published']
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("blog:blog_detail", args=[self.object.pk])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
        <header>
            <div class="col-8 " >
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <form method="post">
                            {% csrf_token %}
                            <p> Хотите удалить пост {{ object.title }} ?</p>
                            <button type="submit" class=" btn btn-secondary btn-primary" >
                                Подтвердить
                            </button>
                            <a class="btn btn-secondary btn-primary" type="button" href="{% url 'blog:blog_list' %}">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </header>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{ object.slug }}</h1>
        </div>
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <div class="card" style="width: 18rem;">
                                <img src="{{ object.image | media_filter }}" class="card-img-top" alt="...">
                            </div>
                            <table class="table table-striped">
                                <tr>
                                    <td>заголовок: {{ object.title }}</td>
                                    <td>содержание: {{ object.content }}p.</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
        <header>
            <div class="col-8 " >
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class=" btn btn-secondary btn-primary" >
                                {% if object %}
                                Изменить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </header>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Все посты</h1>
        </div>

        {% for blog in object_list %}
        {% if blog.is_published %}
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <h4>

                                        <td>{{ blog.title }}</td>
                                        <td>{{ blog.content | truncatechars:100}}</td>

                                    </h4>
                                </tr>

                            </table>
                                    <a class="btn btn-secondary btn-primary" type="button" href="{% url 'blog:blog_detail' blog.pk %}">Открыть</a>
                                    <a class="btn btn-secondary btn-primary" type="button" href="{% url 'blog:blog_edit' blog.pk %}">Изменить</a>
                                    <a class="btn btn-secondary btn-primary" type="button" href="{% url 'blog:blog_delete' blog.pk %}">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <h4>

                                        <td>нет опубликованных записей</td>
                                    </h4>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        <div class="card">
            <div class="card-body">
                <a class="btn btn-secondary btn-primary" type="button" href="{% url 'blog:blog_create' %}">Создать пост</a>
            </div>
        </div>
{% endblock %}