blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogDeleteView, BlogUpdateView, BlogDetailView, BlogListView

app_name = BlogConfig.name
urlpatterns = [
    path("blog/", BlogCreateView.as_view(), name="blog_create"),
    path("blog_list/blog/", BlogListView.as_view(), name="blog_list"),
    path("blog_detail/blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("edit/blog/<int:pk>/", BlogUpdateView.as_view(), name="blog_edit"),
    path("delete/blog/<int:pk>/",BlogDeleteView.as_view(), name="blog_delete"),

]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import (HomePageView, BasePageView, ContactsPageView, ProductListView,
                           ProductDetailView, CategoryListView, CategoryDetailView, ProductCreateView,
                           ProductUpdateView, ProductDeleteView)


app_name = CatalogConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("product_create/catalog", ProductCreateView.as_view(), name="product_create"),
    path("product_list/catalog", ProductListView.as_view(), name="product_list"),
    path("product_detail/catalog/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("product_edit/catalog/<int:pk>/", ProductUpdateView.as_view(), name="product_edit"),
    path("product_delete/catalog/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"),
    path("category/catalog/", CategoryListView.as_view(), name="category"),
    path("base/", BasePageView.as_view(), name="base"),
    path("category_review/catalog/<int:pk>/", CategoryDetailView.as_view(), name="category_review"),



]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="название категории")
    description = models.TextField(verbose_name="описание категории")

    def __str__(self):
        return f"{self.name}: {self.description}"

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="название продукта")
    description = models.TextField(verbose_name="описание продукта")
    image = models.ImageField(
        upload_to="product/image",
        verbose_name="изображение продукта",
        blank=True,
        null=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="категория",
        related_name="products",
    )
    price = models.FloatField(verbose_name="цена продукта")
    created_at = models.DateField(verbose_name="дата создания записи о продукте")
    updated_at = models.DateField(verbose_name="дата изменения записи о продукте")

    def __str__(self):
        return f"{self.name}: {self.description}, цена: {self.price}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["name", "price", "category"]

catalog/forms.py
from django import forms
from catalog.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_name = self.cleaned_data.get('name')
        if cleaned_name in ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']:
            raise forms.ValidationError("Вы не можете добавить продукт c таким именем")
        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data.get('description')
        if cleaned_description in ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']:
            raise forms.ValidationError("Вы не можете добавить продукт c таким описанием")
        return cleaned_description

catalog/views.py
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, TemplateView, CreateView, UpdateView, DeleteView
from django.utils.text import slugify

from catalog.forms import ProductForm
from catalog.models import Product, Category
from version.forms import VersionForm
from version.models import Version


class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ContactsPageView(TemplateView):
    template_name = "contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm

    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("catalog:product_detail", args=[self.object.pk])


class ProductListView(ListView):
    model = Product


class CategoryListView(ListView):
    model = Category


class BasePageView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == "POST":
            context_data['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))
    def get_success_url(self):
        return reverse_lazy("catalog:product_detail", args=[self.object.pk])


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")


class CategoryDetailView(DetailView):
    model = Category

catalog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>One-click-product</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">One-click</h5>
    {% include 'includes/inc_menu.html' %}
</div>
{% block content %}

{% endblock %}

 <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                One-click
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/category.html
{% extends 'base.html' %}
{% block content %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Все категории</h1>
        </div>
        {% for category in categories %}
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <h4>
                                    <a class="text-black" href="{% url 'catalog:category_review' %}">{{ category.name }}</a>
                                    <td>{{ category.description }}</td>
                                    </h4>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}

catalog/templates/category_review.html
{% extends 'base.html' %}
{% block content %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4"> Категория </h1>
        </div>
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <td class="w-25"> None </td>
                                    <td> None </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

catalog/templates/contacts.html
{% extends 'base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-secondary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">One-click</h1>
    <p class="lead">One-click - выбирай что нужно и делай покупки в один клик!</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-4-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный каталог товаров </h4>
                </div>
                <div class="card-body">
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:category' %}">Выбрать категорию товара</a>

                        <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:product_list' %}">Все товары</a>


                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/product.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Все товары</h1>
        </div>
        {% for product in products %}
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <h4>
                                        <div class="card" style="width: 18rem;">
                                            <img src="{{ product.image | media_filter }}" class="card-img-top" alt="...">
                                        </div>
                                        <a class="text-black" href="{% url 'catalog:product_review' product.pk %}">{{ product.name }} </a>
                                        <td>{{ product.description | truncatechars:100}}</td>
                                    </h4>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}

catalog/templates/product_review.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{ product.name }}</h1>
        </div>
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <div class="card" style="width: 18rem;">
                                <img src="{{ product.image | media_filter }}" class="card-img-top" alt="...">
                            </div>
                            <table class="table table-striped">
                                <tr>
                                    <td>описание: {{ product.description }}</td>
                                    <td>цена: {{ product.price }}p.</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}