blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogDeleteView, BlogUpdateView, BlogDetailView, BlogListView

app_name = BlogConfig.name
urlpatterns = [
    path("blog/", BlogCreateView.as_view(), name="blog_create"),
    path("blog_list/blog/", BlogListView.as_view(), name="blog_list"),
    path("blog_detail/blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("edit/blog/<int:pk>/", BlogUpdateView.as_view(), name="blog_edit"),
    path("delete/blog/<int:pk>/",BlogDeleteView.as_view(), name="blog_delete"),

]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import (HomePageView, BasePageView, ContactsPageView, ProductListView,
                           ProductDetailView, CategoryListView, CategoryDetailView, ProductCreateView,
                           ProductUpdateView, ProductDeleteView)


app_name = CatalogConfig.name

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("product_create/catalog", ProductCreateView.as_view(), name="product_create"),
    path("product_list/catalog", ProductListView.as_view(), name="product_list"),
    path("product_detail/catalog/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("product_edit/catalog/<int:pk>/", ProductUpdateView.as_view(), name="product_edit"),
    path("product_delete/catalog/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"),
    path("category/catalog/", CategoryListView.as_view(), name="category"),
    path("base/", BasePageView.as_view(), name="base"),
    path("category_review/catalog/<int:pk>/", CategoryDetailView.as_view(), name="category_review"),



]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="заголовок")
    slug = models.CharField(max_length=100, verbose_name="slug")
    content = models.TextField(verbose_name='содержимое')
    image_preview = models.ImageField(
        upload_to="blog/image",
        verbose_name="предварительный просмотр",
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")
    is_published = models.BooleanField(default=False, verbose_name="опубликованные посты")
    views_count = models.PositiveIntegerField(default=0, verbose_name="количество просмотров")

    def __str__(self):
        return f"{self.title}: {self.content}"

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ["title", "slug"]

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="название категории")
    description = models.TextField(verbose_name="описание категории")

    def __str__(self):
        return f"{self.name}: {self.description}"

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="название продукта")
    description = models.TextField(verbose_name="описание продукта")
    image = models.ImageField(
        upload_to="product/image",
        verbose_name="изображение продукта",
        blank=True,
        null=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="категория",
        related_name="products",
    )
    price = models.FloatField(verbose_name="цена продукта")
    created_at = models.DateField(verbose_name="дата создания записи о продукте")
    updated_at = models.DateField(verbose_name="дата изменения записи о продукте")

    def __str__(self):
        return f"{self.name}: {self.description}, цена: {self.price}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["name", "price", "category"]

blog/forms.py
from django import forms
from blog.models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'is_published']

catalog/forms.py
from django import forms
from catalog.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_name = self.cleaned_data.get('name')
        if cleaned_name in ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']:
            raise forms.ValidationError("Вы не можете добавить продукт c таким именем")
        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data.get('description')
        if cleaned_description in ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']:
            raise forms.ValidationError("Вы не можете добавить продукт c таким описанием")
        return cleaned_description

blog/views.py
from django.shortcuts import render
from django.utils.text import slugify

from blog.forms import BlogForm
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, TemplateView, CreateView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm

    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("blog:blog_detail", args=[self.object.pk])


class BlogListView(ListView):
    model = Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        return obj


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm
    #fields = ['title', 'content', 'is_published']
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("blog:blog_detail", args=[self.object.pk])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

catalog/views.py
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, TemplateView, CreateView, UpdateView, DeleteView
from django.utils.text import slugify

from catalog.forms import ProductForm
from catalog.models import Product, Category
from version.forms import VersionForm
from version.models import Version


class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ContactsPageView(TemplateView):
    template_name = "contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm

    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("catalog:product_detail", args=[self.object.pk])


class ProductListView(ListView):
    model = Product


class CategoryListView(ListView):
    model = Category


class BasePageView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProductDetailView(DetailView):
    model = Product


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == "POST":
            context_data['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))
    def get_success_url(self):
        return reverse_lazy("catalog:product_detail", args=[self.object.pk])


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")


class CategoryDetailView(DetailView):
    model = Category

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
        <header>
            <div class="col-8 " >
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <form method="post">
                            {% csrf_token %}
                            <p> Хотите удалить пост {{ object.title }} ?</p>
                            <button type="submit" class=" btn btn-secondary btn-primary" >
                                Подтвердить
                            </button>
                            <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:blog_list' %}">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </header>
</div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
        <header>
            <div class="col-8 " >
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class=" btn btn-secondary btn-primary" >
                                {% if object %}
                                Изменить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </header>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Все посты</h1>
        </div>

        {% for blog in object_list %}
        {% if blog.is_published %}
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <h4>

                                        <td>{{ blog.title }}</td>
                                        <td>{{ blog.content | truncatechars:100}}</td>

                                    </h4>
                                </tr>

                            </table>
                                    <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:blog_detail' blog.pk %}">Открыть</a>
                                    <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:blog_edit' blog.pk %}">Изменить</a>
                                    <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:blog_delete' blog.pk %}">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <h4>

                                        <td>нет опубликованных записей</td>
                                    </h4>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        <div class="card">
            <div class="card-body">
                <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:blog_create' %}">Создать пост</a>
            </div>
        </div>
{% endblock %}

catalog/templates/catalog/category_detail.html
{% extends 'base.html' %}
{% block content %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4"> {{ object.name }} </h1>
        </div>
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <td class="w-25"> {{ object.name }} </td>
                                    <td> {{ object.description }} </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'base.html' %}
{% block content %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Все категории</h1>
        </div>
        {% for category in object_list %}
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <h4>
                                    <a class="text-black" href="{% url 'catalog:category_review' category.pk %}">{{ category.name }}</a>
                                    <td>{{ category.description }}</td>
                                    </h4>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
        <header>
            <div class="col-8 " >
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <form method="post">
                            {% csrf_token %}
                            <p> Хотите удалить продукт {{ object.name }} ?</p>
                            <button type="submit" class=" btn btn-secondary btn-primary" >
                                Подтвердить
                            </button>
                            <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:product_list' %}">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </header>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{ object.name }}</h1>
        </div>
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <div class="card" style="width: 18rem;">
                                <img src="{{ object.image | media_filter }}" class="card-img-top" alt="...">
                            </div>
                            <table class="table table-striped">
                                <tr>
                                    <td>описание: {{ object.description }}</td>
                                    <td>цена: {{ object.price }}p.</td>
                                </tr>
                            </table>
                                    <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:product_edit' product.pk %}">Изменить</a>
                                    <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:product_delete' product.pk %}">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form class='row' method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class=" btn btn-secondary btn-primary" >
                                {% if object %}
                                Изменить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                    </div>
                </div>
            </div>
            <div class="col-6 " >
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                            {{ formset_management_form }}
                            {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% endfor %}
                    </div>
                </div>
            </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
    <div class="card">
            <div class="card-body">
                <a class="btn btn-secondary btn-primary" type="button" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
            </div>
    </div>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Все товары</h1>
        </div>
        {% for product in object_list %}
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <table class="table table-striped">
                                <tr>
                                    <h4>
                                        <div class="card" style="width: 18rem;">
                                            <img src="{{ product.image | media_filter }}" class="card-img-top" alt="...">
                                        </div>
                                        <a class="text-black" href="{% url 'catalog:product_detail' product.pk %}">{{ product.name }} </a>
                                        <td>{{ product.description | truncatechars:100}}</td>
                                    </h4>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}